Repository openshift/ingress-node-firewall, pull requests merged in 2022-09, with the labels that each got.

#158 Avoid mutating nodeState object directly to avoid race conditions
  controllers/ingressnodefirewall_controller.go
  controllers/ingressnodefirewall_controller_rules_test.go
Labels: approved, lgtm

#162 Create manifest folder for ART to be able to build operator bundle
  Makefile
  manifests/art.yaml
  manifests/ingress-node-firewall.package.yaml
  manifests/stable/ingress-node-firewall-controller-manager-metrics_v1_service.yaml
  manifests/stable/ingress-node-firewall-daemon-clusterrole-binding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  manifests/stable/ingress-node-firewall-daemon-clusterrole-extra_rbac.authorization.k8s.io_v1_clusterrole.yaml
  manifests/stable/ingress-node-firewall-daemon-metrics_v1_service.yaml
  manifests/stable/ingress-node-firewall-daemon-role-binding_rbac.authorization.k8s.io_v1_rolebinding.yaml
  manifests/stable/ingress-node-firewall-daemon-role-extra_rbac.authorization.k8s.io_v1_role.yaml
  manifests/stable/ingress-node-firewall-daemon_monitoring.coreos.com_v1_servicemonitor.yaml
  manifests/stable/ingress-node-firewall-daemon_v1_serviceaccount.yaml
  manifests/stable/ingress-node-firewall-privileged-scc_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  manifests/stable/ingress-node-firewall-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml
  manifests/stable/ingress-node-firewall-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml
  manifests/stable/ingress-node-firewall-webhook-service_v1_service.yaml
  manifests/stable/ingress-node-firewall.clusterserviceversion.yaml
  manifests/stable/ingressnodefirewall.openshift.io_ingressnodefirewallconfigs.yaml
  manifests/stable/ingressnodefirewall.openshift.io_ingressnodefirewallnodestates.yaml
  manifests/stable/ingressnodefirewall.openshift.io_ingressnodefirewalls.yaml
Labels: approved

#163 Add missing image-references required by ART build
  manifests/stable/image-references
Labels: approved, lgtm

#160 Improvements
  Makefile
  README.md
  hack/set-daemon-image.sh
Labels: approved, lgtm

#164 Fix art.yaml
  manifests/art.yaml
Labels: approved, lgtm

#161 use uint64 for statistics update to fix #159
  pkg/metrics/statistics.go
Labels: approved, lgtm

#165 remove debug images name and point to ocp images
  Makefile
  bundle/manifests/ingress-node-firewall.clusterserviceversion.yaml
  config/manager/env.yaml
  config/manager/kustomization.yaml
  manifests/stable/ingress-node-firewall.clusterserviceversion.yaml
Labels: approved, lgtm

#167 Fix missing namespace declaration for OCP
  config/openshift/kustomization.yaml
Labels: approved, lgtm

#168 Fix image-references
  manifests/stable/image-references
Labels: approved, lgtm

#172 Order overlap check should be done between different rules
  pkg/webhook/webhook.go
Labels: approved, lgtm

#184 openshift-ci: Fix CSV images
  openshift-ci/deploy_ingress_node_firewall.sh
Labels: approved, lgtm

#191 OCPBUGS-1621: fix version to allow art build with the proper version with timestamp
  Makefile
  bundle/manifests/ingress-node-firewall.clusterserviceversion.yaml
  config/manifests/bases/ingress-node-firewall.clusterserviceversion.yaml
  config/olm-install/install-resources.yaml
  manifests/stable/ingress-node-firewall.clusterserviceversion.yaml
  openshift-ci/wait_for_csv.sh
  pkg/version/version.go
Labels: bugzilla/valid-bug, jira/valid-bug, approved, lgtm

#115 create-kind-cluster now deploys ingress controller as well
  .gitignore
  Makefile
  README.md
  hack/kind-cluster.sh
  hack/set-daemon-image.sh
Labels: approved, lgtm

#196 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: approved

#197 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: approved
