Repository openshift/ingress-node-firewall, pull requests merged in 2022-10, with the labels that each got.

#195 User should be able to configure deny all rule for zero trust
  api/v1alpha1/ingressnodefirewall_types.go
  bpf/ingress_node_firewall.h
  bpf/ingress_node_firewall_kernel.c
  bundle/manifests/ingressnodefirewall.openshift.io_ingressnodefirewallnodestates.yaml
  bundle/manifests/ingressnodefirewall.openshift.io_ingressnodefirewalls.yaml
  config/crd/bases/ingressnodefirewall.openshift.io_ingressnodefirewallnodestates.yaml
  config/crd/bases/ingressnodefirewall.openshift.io_ingressnodefirewalls.yaml
  config/samples/ingressnodefirewall-demo-denyall.yaml
  manifests/stable/ingressnodefirewall.openshift.io_ingressnodefirewallnodestates.yaml
  manifests/stable/ingressnodefirewall.openshift.io_ingressnodefirewalls.yaml
  pkg/ebpf/bpf_bpfeb.o
  pkg/ebpf/bpf_bpfel.o
  pkg/ebpf/ingress_node_firewall_loader.go
  pkg/failsaferules/failsaferules.go
  pkg/webhook/webhook.go
Labels: approved, lgtm

#200 fix doing multiple detach in ebpfsyncer
  pkg/ebpfsyncer/ebpfsyncer.go
Labels: approved, lgtm

#201 Add license file and fix some bad indentations in the C code
  LICENSE
  bpf/ingress_node_firewall.h
  bpf/ingress_node_firewall_kernel.c
  pkg/ebpf/bpf_bpfeb.go
  pkg/ebpf/bpf_bpfeb.o
  pkg/ebpf/bpf_bpfel.go
  pkg/ebpf/bpf_bpfel.o
Labels: approved

#202 fix some spaces issues
  bpf/ingress_node_firewall_kernel.c
Labels: approved

#209 OCPBUGS-2316: Mixing ICMP v4 and v6 config causes a panic
  Makefile
  api/v1alpha1/ingressnodefirewall_types.go
  bundle/manifests/ingressnodefirewall.openshift.io_ingressnodefirewallnodestates.yaml
  bundle/manifests/ingressnodefirewall.openshift.io_ingressnodefirewalls.yaml
  config/crd/bases/ingressnodefirewall.openshift.io_ingressnodefirewallnodestates.yaml
  config/crd/bases/ingressnodefirewall.openshift.io_ingressnodefirewalls.yaml
  hack/kind-cluster.sh
  manifests/stable/ingressnodefirewall.openshift.io_ingressnodefirewallnodestates.yaml
  manifests/stable/ingressnodefirewall.openshift.io_ingressnodefirewalls.yaml
  pkg/webhook/webhook.go
  pkg/webhook/webhook_suite_test.go
Labels: bugzilla/valid-bug, jira/valid-bug, jira/severity-important, approved, lgtm

#173 OCPBUGS-2325: Add E2E test cases for ingress
  Makefile
  README.md
  openshift-ci/run_e2e.sh
  test/README.md
  test/e2e/daemonset/daemonset.go
  test/e2e/events/events.go
  test/e2e/exec/exec.go
  test/e2e/functional/tests/e2e.go
  test/e2e/icmp/icmp.go
  test/e2e/images/images.go
  test/e2e/ingress-node-firewall/ingress-node-firewall.go
  test/e2e/node/node.go
  test/e2e/pods/pods.go
  test/e2e/transport/transport.go
  test/e2e/validation/tests/validation.go
Labels: bugzilla/valid-bug, jira/severity-critical, jira/valid-bug, approved, lgtm

#219 Fix some new lint errors
  test/e2e/exec/exec.go
  test/e2e/functional/tests/e2e.go
Labels: approved, lgtm

#220 E2E test: only pay attention to internal IPs only and explicitly check for ipv6 address
  test/e2e/node/node.go
Labels: approved, lgtm

#218 Fix #217 apply rules only for valid interface(s) instead of rejecting the whole config
  pkg/ebpf/ingress_node_firewall_loader.go
  pkg/ebpfsyncer/ebpfsyncer.go
  test/e2e/functional/tests/e2e.go
  test/e2e/ingress-node-firewall/ingress-node-firewall.go
Labels: approved, lgtm

#223 Fix #222 after pod restart bpf maps are gone
  bindata/manifests/daemon/daemonset.yaml
  controllers/ingressnodefirewallconfig_controller_test.go
  hack/kind-cluster.sh
  pkg/ebpf/ingress_node_firewall_loader.go
  pkg/ebpfsyncer/ebpfsyncer.go
Labels: approved, lgtm

#225 E2E fixes: switch to smaller image and fix ipv4 only cluster detection
  test/Dockerfile.netcat
  test/e2e/functional/tests/e2e.go
  test/e2e/images/images.go
  test/e2e/node/node.go
  test/e2e/transport/transport.go
Labels: approved, lgtm

#228 E2E tests: Add KinD IPV6 known issue to README
  README.md
  test/README.md
Labels: approved, lgtm

#229 Fix #227: switch to alpine image for bpf mount daemonset
  hack/kind-cluster.sh
Labels: approved, lgtm
