Repository openshift/ingress-node-firewall, pull requests merged in 2022-11, with the labels that each got.

#230 OCPBUGS-2934: unlink events unix socket during shutdown
  cmd/syslog/syslog.go
Labels: bugzilla/valid-bug, jira/valid-bug, approved, lgtm

#234 OCPBUGS-1435: added suggest ns to manifest
  bundle/manifests/ingress-node-firewall.clusterserviceversion.yaml
  config/manifests/bases/ingress-node-firewall.clusterserviceversion.yaml
  manifests/stable/ingress-node-firewall.clusterserviceversion.yaml
Labels: bugzilla/valid-bug, jira/severity-moderate, jira/valid-bug, approved, lgtm

#247 OCPBUGS-1435: use openshift infw namespace
  bundle/manifests/ingress-node-firewall.clusterserviceversion.yaml
  config/manifests/bases/ingress-node-firewall.clusterserviceversion.yaml
  manifests/stable/ingress-node-firewall.clusterserviceversion.yaml
Labels: bugzilla/valid-bug, jira/severity-moderate, jira/valid-bug, approved, lgtm

#249 Bump version to 4.13
  Makefile
  bundle/manifests/ingress-node-firewall.clusterserviceversion.yaml
  config/manifests/bases/ingress-node-firewall.clusterserviceversion.yaml
  config/olm-install/install-resources.yaml
  manifests/art.yaml
  manifests/ingress-node-firewall.package.yaml
  manifests/stable/ingress-node-firewall.clusterserviceversion.yaml
  openshift-ci/wait_for_csv.sh
  pkg/version/version.go
Labels: approved, lgtm

#251 OCPBUGS-1328: fix incorrect link field setting
  bundle/manifests/ingress-node-firewall.clusterserviceversion.yaml
  config/manifests/bases/ingress-node-firewall.clusterserviceversion.yaml
  manifests/stable/ingress-node-firewall.clusterserviceversion.yaml
Labels: bugzilla/valid-bug, jira/severity-moderate, jira/valid-bug, approved, lgtm

#254 [release-4.12] OCPBUGS-1328: additional ingress node firewall operator missing fields
  bundle/manifests/ingress-node-firewall.clusterserviceversion.yaml
  config/manifests/bases/ingress-node-firewall.clusterserviceversion.yaml
  manifests/stable/ingress-node-firewall.clusterserviceversion.yaml
Labels: bugzilla/valid-bug, jira/severity-moderate, cherry-pick-approved, jira/valid-bug, approved, lgtm

#255 OCPBUGS-3880: update ingress node firewall logo
  bundle/manifests/ingress-node-firewall.clusterserviceversion.yaml
  config/manifests/bases/ingress-node-firewall.clusterserviceversion.yaml
  manifests/stable/ingress-node-firewall.clusterserviceversion.yaml
Labels: bugzilla/valid-bug, jira/valid-bug, approved, lgtm

#257 update operator image to 4.13
  bundle/manifests/ingress-node-firewall.clusterserviceversion.yaml
  config/manifests/bases/ingress-node-firewall.clusterserviceversion.yaml
  manifests/stable/ingress-node-firewall.clusterserviceversion.yaml
Labels: approved, lgtm

#258 fix naming convention
  manifests/art.yaml
Labels: approved, lgtm

#260 Update README.md and misc repo cleanup
  README.md
  api/v1alpha1/ingressnodefirewallnodestate_types.go
  bundle/manifests/ingressnodefirewall.openshift.io_ingressnodefirewallnodestates.yaml
  config/crd/bases/ingressnodefirewall.openshift.io_ingressnodefirewallnodestates.yaml
  controllers/ingressnodefirewallconfig_controller_test.go
  logo.jpg
  manifests/stable/ingressnodefirewall.openshift.io_ingressnodefirewallnodestates.yaml
  pkg/ebpf/ingress_node_firewall_loader.go
  pkg/utils/utils.go
Labels: approved
