Repository openshift/ingress-node-firewall, pull requests merged in 2023-11, with the labels that each got.

#432 OCPBUGS-22765:replace ingress node firewall container image to match ART's name
  bundle/manifests/ingress-node-firewall.clusterserviceversion.yaml
  config/manifests/bases/ingress-node-firewall.clusterserviceversion.yaml
  config/openshift-olm/kustomization.yaml
  manifests/stable/ingress-node-firewall.clusterserviceversion.yaml
Labels: cherry-pick-approved, jira/severity-critical, jira/valid-bug, backport-risk-assessed, approved, lgtm, jira/valid-reference

#433 OCPBUGS-22766:replace ingress node firewall container image to match ART image
  bundle/manifests/ingress-node-firewall.clusterserviceversion.yaml
  config/manifests/bases/ingress-node-firewall.clusterserviceversion.yaml
  config/openshift-olm/kustomization.yaml
  manifests/stable/ingress-node-firewall.clusterserviceversion.yaml
Labels: cherry-pick-approved, jira/severity-critical, jira/valid-bug, backport-risk-assessed, approved, lgtm, jira/valid-reference

#434 OCPBUGS-22768:replace ingress node firewall container image to match ART
  bundle/manifests/ingress-node-firewall.clusterserviceversion.yaml
  config/manifests/bases/ingress-node-firewall.clusterserviceversion.yaml
  manifests/stable/ingress-node-firewall.clusterserviceversion.yaml
Labels: cherry-pick-approved, jira/valid-bug, backport-risk-assessed, jira/severity-important, approved, lgtm, jira/valid-reference

#436 update golang to 1.21 since cilium latest requires go1.20
  Dockerfile
  Dockerfile.daemon
Labels: approved, lgtm

#447 prevent empty interfaces and configs
  Dockerfile
  api/v1alpha1/ingressnodefirewall_types.go
  bundle/manifests/ingressnodefirewall.openshift.io_ingressnodefirewalls.yaml
  config/crd/bases/ingressnodefirewall.openshift.io_ingressnodefirewalls.yaml
  controllers/ingressnodefirewall_controller_rules_test.go
  manifests/stable/ingressnodefirewall.openshift.io_ingressnodefirewalls.yaml
  pkg/webhook/webhook_suite_test.go
Labels: approved, lgtm

#446 Update ingressnodefirewall_types.go
  api/v1alpha1/ingressnodefirewall_types.go
Labels: needs-ok-to-test
